site_name: gcontext
site_url: http://abetkin.github.io/gcontext/
site_description: The global context in use.

repo_url: https://github.com/abetkin/gcontext

pages:
- ['index.md', 'Home']
- ['examples.md', 'Examples']

